// Auth Action Types
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Register Action Types
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Profile Action Types
export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// Job Action Types
export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';
export const FETCH_JOB_DETAILS_START = 'FETCH_JOB_DETAILS_START';
export const FETCH_JOB_DETAILS_SUCCESS = 'FETCH_JOB_DETAILS_SUCCESS';
export const FETCH_JOB_DETAILS_FAIL = 'FETCH_JOB_DETAILS_FAIL';
export const CLEAR_JOB_DETAILS = 'CLEAR_JOB_DETAILS';

// Referral Action Types
export const FETCH_REFERRALS_START = 'FETCH_REFERRALS_START';
export const FETCH_REFERRALS_SUCCESS = 'FETCH_REFERRALS_SUCCESS';
export const FETCH_REFERRALS_FAIL = 'FETCH_REFERRALS_FAIL';
export const FETCH_REFERRAL_DETAILS_START = 'FETCH_REFERRAL_DETAILS_START';
export const FETCH_REFERRAL_DETAILS_SUCCESS = 'FETCH_REFERRAL_DETAILS_SUCCESS';
export const FETCH_REFERRAL_DETAILS_FAIL = 'FETCH_REFERRAL_DETAILS_FAIL';
export const CREATE_REFERRAL_REQUEST_START = 'CREATE_REFERRAL_REQUEST_START';
export const CREATE_REFERRAL_REQUEST_SUCCESS = 'CREATE_REFERRAL_REQUEST_SUCCESS';
export const CREATE_REFERRAL_REQUEST_FAIL = 'CREATE_REFERRAL_REQUEST_FAIL';
export const UPDATE_REFERRAL_STATUS_START = 'UPDATE_REFERRAL_STATUS_START';
export const UPDATE_REFERRAL_STATUS_SUCCESS = 'UPDATE_REFERRAL_STATUS_SUCCESS';
export const UPDATE_REFERRAL_STATUS_FAIL = 'UPDATE_REFERRAL_STATUS_FAIL';
export const CLEAR_REFERRAL_DETAILS = 'CLEAR_REFERRAL_DETAILS';
export const CLEAR_REFERRAL_ERROR = 'CLEAR_REFERRAL_ERROR';

// UI Action Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ'; 