// Auth Action Types
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// Register Action Types
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Profile Action Types
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';
export const EXPERIENCE_ADD_SUCCESS = 'EXPERIENCE_ADD_SUCCESS';
export const EXPERIENCE_ADD_ERROR = 'EXPERIENCE_ADD_ERROR';
export const EXPERIENCE_DELETE_SUCCESS = 'EXPERIENCE_DELETE_SUCCESS';
export const EXPERIENCE_DELETE_ERROR = 'EXPERIENCE_DELETE_ERROR';
export const EDUCATION_ADD_SUCCESS = 'EDUCATION_ADD_SUCCESS';
export const EDUCATION_ADD_ERROR = 'EDUCATION_ADD_ERROR';
export const EDUCATION_DELETE_SUCCESS = 'EDUCATION_DELETE_SUCCESS';
export const EDUCATION_DELETE_ERROR = 'EDUCATION_DELETE_ERROR';
export const SKILL_ADD_SUCCESS = 'SKILL_ADD_SUCCESS';
export const SKILL_ADD_ERROR = 'SKILL_ADD_ERROR';
export const SKILL_DELETE_SUCCESS = 'SKILL_DELETE_SUCCESS';
export const SKILL_DELETE_ERROR = 'SKILL_DELETE_ERROR';

// Job Action Types
export const JOBS_LOADING = 'JOBS_LOADING';
export const JOBS_SUCCESS = 'JOBS_SUCCESS';
export const JOBS_ERROR = 'JOBS_ERROR';
export const JOB_DETAIL_LOADING = 'JOB_DETAIL_LOADING';
export const JOB_DETAIL_SUCCESS = 'JOB_DETAIL_SUCCESS';
export const JOB_DETAIL_ERROR = 'JOB_DETAIL_ERROR';
export const JOB_CREATE_LOADING = 'JOB_CREATE_LOADING';
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS';
export const JOB_CREATE_ERROR = 'JOB_CREATE_ERROR';
export const JOB_UPDATE_LOADING = 'JOB_UPDATE_LOADING';
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS';
export const JOB_UPDATE_ERROR = 'JOB_UPDATE_ERROR';
export const JOB_DELETE_SUCCESS = 'JOB_DELETE_SUCCESS';
export const JOB_DELETE_ERROR = 'JOB_DELETE_ERROR';
export const JOB_SEARCH_SUCCESS = 'JOB_SEARCH_SUCCESS';
export const JOB_SEARCH_ERROR = 'JOB_SEARCH_ERROR';
export const TOP_JOBS_SUCCESS = 'TOP_JOBS_SUCCESS';
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCCESS';
export const SAVED_JOBS_LOADING = 'SAVED_JOBS_LOADING';
export const SAVED_JOBS_SUCCESS = 'SAVED_JOBS_SUCCESS';
export const SAVED_JOBS_ERROR = 'SAVED_JOBS_ERROR';

// Company Action Types
export const COMPANIES_LOADING = 'COMPANIES_LOADING';
export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';
export const COMPANIES_ERROR = 'COMPANIES_ERROR';
export const COMPANY_DETAIL_LOADING = 'COMPANY_DETAIL_LOADING';
export const COMPANY_DETAIL_SUCCESS = 'COMPANY_DETAIL_SUCCESS';
export const COMPANY_DETAIL_ERROR = 'COMPANY_DETAIL_ERROR';
export const TOP_COMPANIES_SUCCESS = 'TOP_COMPANIES_SUCCESS';

// Referral Action Types
export const REFERRALS_LOADING = 'REFERRALS_LOADING';
export const REFERRALS_SUCCESS = 'REFERRALS_SUCCESS';
export const REFERRALS_ERROR = 'REFERRALS_ERROR';
export const REFERRAL_DETAIL_LOADING = 'REFERRAL_DETAIL_LOADING';
export const REFERRAL_DETAIL_SUCCESS = 'REFERRAL_DETAIL_SUCCESS';
export const REFERRAL_DETAIL_ERROR = 'REFERRAL_DETAIL_ERROR';
export const REFERRAL_CREATE_LOADING = 'REFERRAL_CREATE_LOADING';
export const REFERRAL_CREATE_SUCCESS = 'REFERRAL_CREATE_SUCCESS';
export const REFERRAL_CREATE_ERROR = 'REFERRAL_CREATE_ERROR';
export const REFERRAL_UPDATE_LOADING = 'REFERRAL_UPDATE_LOADING';
export const REFERRAL_UPDATE_SUCCESS = 'REFERRAL_UPDATE_SUCCESS';
export const REFERRAL_UPDATE_ERROR = 'REFERRAL_UPDATE_ERROR';
export const REFERRAL_NOTE_ADD_SUCCESS = 'REFERRAL_NOTE_ADD_SUCCESS';

// Statistics Action Types
export const STATS_LOADING = 'STATS_LOADING';
export const STATS_SUCCESS = 'STATS_SUCCESS';
export const STATS_ERROR = 'STATS_ERROR';
export const USER_STATS_LOADING = 'USER_STATS_LOADING';
export const USER_STATS_SUCCESS = 'USER_STATS_SUCCESS';
export const USER_STATS_ERROR = 'USER_STATS_ERROR';

// Notification Action Types
export const FETCH_NOTIFICATIONS_LOADING = 'FETCH_NOTIFICATIONS_LOADING';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';

// UI Action Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_NOTIFICATION_PANEL = 'TOGGLE_NOTIFICATION_PANEL';
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ'; 